#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v25
# autospec commit: 9594167
#
Name     : compat-libxml2-soname2
Version  : 2.13.6
Release  : 3
URL      : https://download.gnome.org/sources/libxml2/2.13/libxml2-2.13.6.tar.xz
Source0  : https://download.gnome.org/sources/libxml2/2.13/libxml2-2.13.6.tar.xz
Summary  : libXML library version2.
Group    : Development/Tools
License  : MIT
Requires: compat-libxml2-soname2-lib = %{version}-%{release}
Requires: compat-libxml2-soname2-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : buildreq-gnome
BuildRequires : bzip2-dev
BuildRequires : file
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pkgconfig(zlib)
BuildRequires : python3-dev
BuildRequires : zlib-dev
BuildRequires : zlib-dev32
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: stateless.patch

%description
Module libxml2-python
=====================
This is the libxml2 python module, providing access to the
libxml2 and libxslt (if available) libraries. For general
informationss on those XML and XSLT libraries check their
web pages at:
https://gitlab.gnome.org/GNOME/libxml2/-/wikis/home
and
https://gitlab.gnome.org/GNOME/libxslt/-/wikis/home

%package lib
Summary: lib components for the compat-libxml2-soname2 package.
Group: Libraries
Requires: compat-libxml2-soname2-license = %{version}-%{release}

%description lib
lib components for the compat-libxml2-soname2 package.


%package license
Summary: license components for the compat-libxml2-soname2 package.
Group: Default

%description license
license components for the compat-libxml2-soname2 package.


%prep
%setup -q -n libxml2-2.13.6
cd %{_builddir}/libxml2-2.13.6
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1745345665
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-http \
--without-lzma
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1745345665
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-libxml2-soname2
cp %{_builddir}/libxml2-%{version}/Copyright %{buildroot}/usr/share/package-licenses/compat-libxml2-soname2/8b8a61fcd505743acbe94866f4f73b2fdf1f359f || :
export GOAMD64=v2
GOAMD64=v2
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/xml2-config
rm -f %{buildroot}*/usr/bin/xmlcatalog
rm -f %{buildroot}*/usr/bin/xmllint
rm -f %{buildroot}*/usr/include/libxml2/libxml/HTMLparser.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/HTMLtree.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/SAX.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/SAX2.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/c14n.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/catalog.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/chvalid.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/debugXML.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/dict.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/encoding.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/entities.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/globals.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/hash.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/list.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/nanoftp.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/nanohttp.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/parser.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/parserInternals.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/pattern.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/relaxng.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/schemasInternals.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/schematron.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/threads.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/tree.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/uri.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/valid.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xinclude.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xlink.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlIO.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlautomata.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlerror.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlexports.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlmemory.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlmodule.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlreader.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlregexp.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlsave.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlschemas.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlschemastypes.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlstring.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlunicode.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlversion.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xmlwriter.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xpath.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xpathInternals.h
rm -f %{buildroot}*/usr/include/libxml2/libxml/xpointer.h
rm -f %{buildroot}*/usr/lib/python3.13/site-packages/__pycache__/drv_libxml2.cpython-313.pyc
rm -f %{buildroot}*/usr/lib/python3.13/site-packages/__pycache__/libxml2.cpython-313.pyc
rm -f %{buildroot}*/usr/lib/python3.13/site-packages/drv_libxml2.py
rm -f %{buildroot}*/usr/lib/python3.13/site-packages/libxml2.py
rm -f %{buildroot}*/usr/lib/python3.13/site-packages/libxml2mod.so
rm -f %{buildroot}*/usr/lib64/cmake/libxml2/libxml2-config.cmake
rm -f %{buildroot}*/usr/lib64/libxml2.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/libxml-2.0.pc
rm -f %{buildroot}*/usr/share/aclocal/libxml.m4
rm -f %{buildroot}*/usr/share/doc/libxml2/xmlcatalog.html
rm -f %{buildroot}*/usr/share/doc/libxml2/xmllint.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/general.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/home.png
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/index.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/left.png
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-HTMLparser.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-HTMLtree.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-SAX.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-SAX2.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-c14n.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-catalog.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-chvalid.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-debugXML.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-dict.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-encoding.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-entities.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-globals.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-hash.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-list.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-nanoftp.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-nanohttp.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-parser.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-parserInternals.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-pattern.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-relaxng.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-schemasInternals.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-schematron.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-threads.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-tree.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-uri.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-valid.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xinclude.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xlink.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlIO.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlautomata.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlerror.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlexports.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlmemory.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlmodule.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlreader.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlregexp.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlsave.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlschemas.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlschemastypes.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlstring.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlunicode.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlversion.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xmlwriter.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xpath.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xpathInternals.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2-xpointer.html
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/libxml2.devhelp2
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/right.png
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/style.css
rm -f %{buildroot}*/usr/share/gtk-doc/html/libxml2/up.png
rm -f %{buildroot}*/usr/share/man/man1/xml2-config.1
rm -f %{buildroot}*/usr/share/man/man1/xmlcatalog.1
rm -f %{buildroot}*/usr/share/man/man1/xmllint.1

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxml2.so.2
/usr/lib64/libxml2.so.2.13.6

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-libxml2-soname2/8b8a61fcd505743acbe94866f4f73b2fdf1f359f
